# Generated by Django 5.2.9 on 2025-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovement',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
