# Generated by Django 5.2.9 on 2025-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_service', '0002_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnserver',
            name='config_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='port',
            field=models.IntegerField(default=443),
        ),
        migrations.AlterField(
            model_name='vpnserver',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
